### ISSUE TITLE
Training file is missing

### ISSUE THREAD

**Issue by arkinrc** [mingyuyng/Visual-Selective-VIO#1]
First of all, I would like to appreciate your great efforts.

I've tested with the provided/default pre-trained models and received quite good results but i am unable to change the fusion methods in order to increase the accuracy due to the pre-trained models were trained with cat fusion method. Hence i would appreciate if you could share the training code/training file of this algorithm.
Email: arkin_8858@yeah.net

Regards
RC. Arkin

**Comment by hiXiaoYU** [comment]
I'm sorry to bother you, but I want to know how to solve this problem 
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from evaluation import kittiOdomEval
ImportError: cannot import name 'kittiOdomEval' from 'evaluation'

**Comment by 2seung0708** [comment]
Hello. I'm having the same problem.
Since there is no training code, it is difficult to apply your method and conduct some experiments.
Could you please share the training code?
Email: 2seung0708@gmail.com
Thank you!

**Comment by zyayoung** [comment]
Thanks for your impressive work!
We would like to build our work on your system.
Do you have a plan to release code for training?

Thank you!
