### ISSUE TITLE
ImportError: cannot import name 'kittiOdomEval' from 'evaluation' 

### ISSUE THREAD

**Issue by hiXiaoYU** [mingyuyng/Visual-Selective-VIO#2]
I'm sorry to bother you, but I want to know how to solve this problem 
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from evaluation import kittiOdomEval
ImportError: cannot import name 'kittiOdomEval' from 'evaluation'

**Comment by arkinrc** [comment]
@hiXiaoYU 
pip install evaluation probably will solve the issue and if with this issue can't be solved then just comment this kittiOdomEval and it will work. it worked in my case.

**Comment by hiXiaoYU** [comment]
@arkinrc 
thank you！I comment this kittiOdomEval and it is working fine. However i meet the same question as you. The train file is missing.

**Comment by hiXiaoYU** [comment]
@arkinrc
Hello, Sorry to bother you.I would like to ask if the author has sent you the train.py file

**Comment by mingyuyng** [comment]
Hi @arkinrc, @hiXiaoYU,

Thanks for pointing this problem out. 'kittiOdomEval' is actually not used in the test file and I already removed it. 

As for the training file, it is still in preparation and not ready for public review yet. It will be released in the future. Sorry for the inconvenience.

**Comment by arkinrc** [comment]
@mingyuyng 
Thank you so much.. looking forward to the train file.

Best
Arkin

**Comment by Xyanpian** [comment]
looking forward to the train file.

**Comment by hiXiaoYU** [comment]
@mingyuyng
Hello, Sorry to bother you again. Could you tell me the format of IMU data you provided? Which columns are the accelerometer or gyroscope?

**Comment by mingyuyng** [comment]
@hiXiaoYU
Sorry for the delay. I have added the IMU data format in README.
